// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: transaction.sql

package db

import (
	"context"
	"time"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO
    transactions (id, from_account_id, to_account_id, amount)
VALUES
    (
        $1,
        $2,
        $3,
        $4
    ) RETURNING id, from_account_id, to_account_id, amount, created_at
`

type CreateTransactionParams struct {
	ID            string
	FromAccountID string
	ToAccountID   string
	Amount        int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.ID,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT
    tx.id, tx.from_account_id, tx.to_account_id, tx.amount, tx.created_at,
    AFr.owner AS from_account_owner,
    ATo.owner AS to_account_owner
FROM
    transactions TX,
    accounts AFr,
    accounts ATo
WHERE
    TX.from_account_id = AFr.id
    AND TX.to_account_id = ATo.id
    AND TX.id = $1
`

type GetTransactionRow struct {
	ID               string
	FromAccountID    string
	ToAccountID      string
	Amount           int64
	CreatedAt        time.Time
	FromAccountOwner string
	ToAccountOwner   string
}

func (q *Queries) GetTransaction(ctx context.Context, id string) (GetTransactionRow, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i GetTransactionRow
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.CreatedAt,
		&i.FromAccountOwner,
		&i.ToAccountOwner,
	)
	return i, err
}
